name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .gcloudignore"
      - poetry.lock"
      - pyproject.toml
      - Procfile

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: production

    env:
      EMAIL_HOST: ${{ vars.EMAIL_HOST }}
      EMAIL_PORT: ${{ vars.EMAIL_PORT }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      GCLOUD_STORAGE_BUCKET_NAME: ${{ vars.GCP_STORAGE_BUCKET_NAME }}
      GCLOUD_STORAGE_BUCKET_LOCATION: ${{ vars.GCP_STORAGE_BUCKET_REGION }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Add .env file
        run: |
          echo "EMAIL_HOST=$EMAIL_HOST" >> .env
          echo "EMAIL_PORT=$EMAIL_PORT" >> .env
          echo "EMAIL_USERNAME=$EMAIL_USERNAME" >> .env
          echo "EMAIL_PASSWORD=$EMAIL_PASSWORD" >> .env
          echo "GCLOUD_STORAGE_BUCKET_NAME=$GCLOUD_STORAGE_BUCKET_NAME" >> .env
          echo "GCLOUD_STORAGE_BUCKET_LOCATION=$GCLOUD_STORAGE_BUCKET_LOCATION" >> .env

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ vars.GCP_CLOUD_RUN_SERVICE }} \
            --source . \
            --region ${{ vars.GCP_REGION }} \
            --project ${{ vars.GCP_PROJECT_ID }} \
            --platform managed \
            --allow-unauthenticated
